#!/bin/bash

readonly S3_URL=http://1000genomes.s3.amazonaws.com/release/20130502/
readonly PEDFILE=integrated_call_samples.20130502.ALL.ped
readonly CHR22=ALL.chr22.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf.gz
readonly BAMS=alignment.index
readonly NSAMPLES=50
readonly OUTPUT_DIR=$( pwd )/${NSAMPLES}_samples

# use gsort/gzcat on OS X 
function gnusort {
    if hash gsort 2>/dev/null
    then
        gsort "$@"
    else
        sort "$@"
    fi
}

function gnuzipcat {
    if hash gzcat 2>/dev/null
    then
        gzcat "$@"
    else
        zcat "$@"
    fi
}

rm -rf ${OUTPUT_DIR}

if [[ ! -f ${CHR22} ]]
then
	remote=${S3_URL}${CHR22}
	echo "Getting ${remote}"
	wget ${remote}
fi

if [[ ! -f ${PEDFILE} ]]
then
	remote=${S3_URL}${PEDFILE}
	echo "Getting ${remote}"
	wget ${remote}
fi

if [[ ! -f ${BAMS} ]]
then
	remote=${S3_URL}../../${BAMS}
	echo "Getting ${remote}"
	wget ${remote}
fi

# pick NSAMPLES samples randomly from those reported in Chr22 VCF and sort them
readonly SAMPLES=$( gnuzipcat ${CHR22} \
			| head -n 1000 \
			| grep CHROM \
			| cut -f10- -d $'\t' \
			| tr $'\t' $'\n' \
			| gnusort -R \
			| head -n ${NSAMPLES} \
			| gnusort \
			| tr $'\n' , \
			| sed -e 's/,$//' )
echo $SAMPLES

python ./server-0.3.4/scripts/download_fuller_example_data.py \
	--force \
	--source s3 \
	--samples ${SAMPLES} \
	--num-reads 1000 \
	--num-chromosomes 24 \
	${OUTPUT_DIR}
