#!/bin/bash

readonly S3_URL=http://1000genomes.s3.amazonaws.com/release/20130502/
readonly PED=integrated_call_samples.20130502.ALL.ped
readonly CHR22=ALL.chr22.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf.gz
readonly BAMS=alignment.index
readonly NSAMPLES=50

if [[ -z "$1" ]] || [[ ! -d "$1" ]] || [[ -z "$2" ]] || [[ ! -d "$2" ]] 
then
	>&2 echo "Usage: $0 /path/to/server-0.3.4 /output/dir"
	>&2 echo "   eg, $0 ./server-0.3.4 /srv/ga4gh"
	>&2 echo "   invocation was: $0 $1 $2"
	exit 1
fi

readonly SERVER_DIR=$1
readonly OUTPUT_DIR=$2/${NSAMPLES}_samples

# use gsort/gzcat on OS X 
function gnusort {
    if hash gsort 2>/dev/null
    then
        gsort "$@"
    else
        sort "$@"
    fi
}

function gnuzipcat {
    if hash gzcat 2>/dev/null
    then
        gzcat "$@"
    else
        zcat "$@"
    fi
}

rm -rf ${OUTPUT_DIR}
mkdir -p ${OUTPUT_DIR}

function get_if_absent {
    local URL=$1
    local file=$2
    
    if [[ ! -f "${file}" ]]
    then
    	echo "Getting ${URL}"
	wget $URL
    fi
}

get_if_absent ${S3_URL}${CHR22} ${CHR22}
get_if_absent ${S3_URL}${PED} ${PED}
get_if_absent ${S3_URL}../../${BAMS} ${BAMS}

# pick NSAMPLES samples randomly from those reported in Chr22 VCF and sort them
readonly SAMPLES=$( gnuzipcat ${CHR22} \
			| head -n 1000 \
			| grep CHROM \
			| cut -f10- -d $'\t' \
			| tr $'\t' $'\n' \
			| gnusort -R \
			| head -n ${NSAMPLES} \
			| gnusort \
			| tr $'\n' , \
			| sed -e 's/,$//' )
echo $SAMPLES

python ${SERVER_DIR}/scripts/download_fuller_example_data.py \
	--force \
	--source s3 \
	--samples ${SAMPLES} \
	--num-reads 1000 \
	--num-chromosomes 24 \
	${OUTPUT_DIR} \
	&& rm -f ${BAMS} ${PED} ${CHR22}
